training:
  batch_size: 8
  num_epochs: 100
  learning_rate: 1e-4
  num_timesteps: 1000
  save_every: 10
  patience: 5

model:
  in_channels: 3
  out_channels: 3
  channels: [64, 128, 256, 512, 1024]
  layers_per_block: 2
  downblock: ResnetDownsampleBlock2D
  upblock: ResnetUpsampleBlock2D
  add_attention: true
  attention_head_dim: 64